# Generated by Django 5.0 on 2023-12-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
