# Generated by Django 4.2.7 on 2023-11-22 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='unique_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
