# Generated by Django 5.0 on 2023-12-05 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0002_alter_userprofiles_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='unique_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
