# Generated by Django 5.0 on 2023-12-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0002_userprofiles_is_staff_alter_savingsaccount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
