# Generated by Django 4.2.7 on 2023-11-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0024_remove_membershares_cyclemeeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpositions',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='constitutiontable',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fines',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupcyclestatus',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='positions',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='sync_flag',
            field=models.IntegerField(default=1),
        ),
    ]
