# Generated by Django 4.2.7 on 2023-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0025_alter_assignedpositions_sync_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='position_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
