# Generated by Django 4.2.7 on 2023-11-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0026_positions_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='constitutiontable',
            name='constitution_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cycleschedules',
            name='schedule_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupfees',
            name='fee_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='member_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='profile_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='users_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
