# Generated by Django 4.2.7 on 2023-11-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0029_alter_assignedpositions_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedpositions',
            name='assign_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignedpositions',
            name='member_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
