# Generated by Django 4.2.7 on 2023-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0030_assignedpositions_assign_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpositions',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
