# Generated by Django 4.2.7 on 2023-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0031_alter_assignedpositions_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfees',
            name='member',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
