# Generated by Django 4.2.7 on 2023-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0032_alter_groupfees_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfees',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
