# Generated by Django 4.2.7 on 2023-11-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0033_alter_groupfees_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitutiontable',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cycleschedules',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='assigned_position_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='constitution_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='cycle_schedule_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='group_member_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupform',
            name='logged_in_users_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
