# Generated by Django 4.2.7 on 2023-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0034_alter_constitutiontable_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupform',
            name='group_profile_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
