# Generated by Django 4.2.7 on 2023-11-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0037_cyclestartmeeting_group_paymentinfo_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activecyclemeeting',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='assignedpositions',
            name='assign_id',
        ),
        migrations.RemoveField(
            model_name='assignedpositions',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='constitutiontable',
            name='constitution_id',
        ),
        migrations.RemoveField(
            model_name='constitutiontable',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='cyclemeeting',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='cycleschedules',
            name='schedule_id',
        ),
        migrations.RemoveField(
            model_name='cycleschedules',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='cyclestartmeeting',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='fines',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='groupcyclestatus',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='groupfees',
            name='fee_id',
        ),
        migrations.RemoveField(
            model_name='groupfees',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='groupform',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='loanapplications',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='loandisbursement',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='loanpayments',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='membershares',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='reversedtransactions',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='savingsaccount',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='shareout',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='social',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='socialfundapplications',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sync_flag',
        ),
        migrations.RemoveField(
            model_name='users',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='welfareaccount',
            name='sync_flag',
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='attendanceData',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='date',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='endTime',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='facilitator',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='meetingPurpose',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='objectives',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='proposals',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='representativeData',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='sharePurchases',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='socialFundContributions',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='time',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='totalLoanFund',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cyclemeeting',
            name='totalSocialFund',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
