# Generated by Django 4.2.7 on 2023-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0039_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='unique_code',
            field=models.TextField(unique=True),
        ),
    ]
