# Generated by Django 4.2.7 on 2023-11-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0041_alter_assignedpositions_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpositions',
            name='position_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
