# Generated by Django 4.2.7 on 2023-11-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0042_alter_assignedpositions_position_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpositions',
            old_name='position_id',
            new_name='position_name',
        ),
    ]
