# Generated by Django 4.2.7 on 2023-11-16 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digi_save_vsla_api', '0043_rename_position_id_assignedpositions_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteUser',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concrete User',
                'verbose_name_plural': 'Concrete Users',
            },
            bases=('digi_save_vsla_api.users',),
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
